# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Jorden Jolley
name                     : &name "Jorden Jolley"
email: jorden.jolley@gmail.com
description: &description # this means to ignore newlines until "baseurl:"
  Jorden Jolley's software engineering portfolio.
twitter_username: JordenJolley
repository: "jordenjolley.github.io"
github_username: jordenjoe
minimal_mistakes_skin: dark
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from


author:
  name   : "Jorden Jolley"
  avatar : "/assets/images/bio-photo.jpg"
  location: "New York, New York, USA"
  bio    : "MS Computer Science Bridge student at Columbia University."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/JordenJolley"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jordenjoe"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jorden-jolley-89b380105/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "hhttps://twitter.com/JordenJolley"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/jordenjoe"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/jorden-jolley-89b380105/"

defaults:
  # _posts
  - scope:
      path: "about"
      type: 
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
    # _portfolio
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      share: false
      comment: false


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/

